name: Hello world workflow
on:
  push:
    branches: [ main ]
  

jobs:
    hello_worlds:
      runs-on: self-hosted
      steps:
        - name: Print Hello world
          run: echo "Hello Universe"
        - uses: actions/checkout@v4
          