name: Hello world workflow
on:
  push:
    branches: [ main ]
  

jobs:
    hello_worlds:
      runs-on: self-hosted
      steps:
        - uses: actions/checkout@v4
        - name: Print Hello world
          run: echo "Hello Universe1"
        
          