name: Hello world workflow
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
    hello_worlds:
      runs-on: self-hosted
      steps:
        - name: Print Hello world
          run: echo "Hello Universe"
          